auth:
  google:
    client-id: 508793857526-hjnar37f3fdnjsopr7lv7dfgkf972p5h.apps.googleusercontent.com
    client-secret: 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
    scope:
      - email
      - profile
    token-req-url : https://oauth2.googleapis.com
  kakao:
    client-id: a8cdfb7c6e1ce33857c1ff4df66c348c
    client-secret: ViVXmJMU0xE6pgqJOTmdc8drLdj3n5BV
    scope:
      - profile_nickname
      - profile_image
      - account_email
  redirect-url: http://localhost:3000

custom:
  jwt:
    secret: jwt시크릿