# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: sswm-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE : sswm
      TZ: Asia/Seoul
    ports:
      - 3306:3306
