# Use postgres/example user/password credentials
version: '3.1'

services:
  database:
    image: mysql:8.0
    container_name: sswm-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE : sswm
      TZ: Asia/Seoul
    ports:
      - 3306:3306
  application:
    build: .
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/sswm
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - 8080:8080
    restart: always